export const CAPITALS: Record<string, string> = {
    "AW": "Oranjestad",
    "AF": "Kabul",
    "AO": "Luanda",
    "AI": "The Valley",
    "AX": "Mariehamn",
    "AL": "Tirana",
    "AD": "Andorra la Vella",
    "AE": "Abu Dhabi",
    "AR": "Buenos Aires",
    "AM": "Yerevan",
    "AS": "Pago Pago",
    "TF": "Port-aux-Fran\u00e7ais",
    "AG": "Saint John's",
    "AU": "Canberra",
    "AT": "Vienna",
    "AZ": "Baku",
    "BI": "Gitega",
    "BE": "Brussels",
    "BJ": "Porto-Novo",
    "BF": "Ouagadougou",
    "BD": "Dhaka",
    "BG": "Sofia",
    "BH": "Manama",
    "BS": "Nassau",
    "BA": "Sarajevo",
    "BL": "Gustavia",
    "SH": "Jamestown",
    "BY": "Minsk",
    "BZ": "Belmopan",
    "BM": "Hamilton",
    "BO": "Sucre",
    "BQ": "Kralendijk",
    "BR": "Bras\u00edlia",
    "BB": "Bridgetown",
    "BN": "Bandar Seri Begawan",
    "BT": "Thimphu",
    "BW": "Gaborone",
    "CF": "Bangui",
    "CA": "Ottawa",
    "CC": "West Island",
    "CH": "Bern",
    "CL": "Santiago",
    "CN": "Beijing",
    "CI": "Yamoussoukro",
    "CM": "Yaound\u00e9",
    "CD": "Kinshasa",
    "CG": "Brazzaville",
    "CK": "Avarua",
    "CO": "Bogot\u00e1",
    "KM": "Moroni",
    "CV": "Praia",
    "CR": "San Jos\u00e9",
    "CU": "Havana",
    "CW": "Willemstad",
    "CX": "Flying Fish Cove",
    "KY": "George Town",
    "CY": "Nicosia",
    "CZ": "Prague",
    "DE": "Berlin",
    "DJ": "Djibouti",
    "DM": "Roseau",
    "DK": "Copenhagen",
    "DO": "Santo Domingo",
    "DZ": "Algiers",
    "EC": "Quito",
    "EG": "Cairo",
    "ER": "Asmara",
    "EH": "El Aai\u00fan",
    "ES": "Madrid",
    "EE": "Tallinn",
    "ET": "Addis Ababa",
    "FI": "Helsinki",
    "FJ": "Suva",
    "FK": "Stanley",
    "FR": "Paris",
    "FO": "T\u00f3rshavn",
    "FM": "Palikir",
    "GA": "Libreville",
    "GB": "London",
    "GE": "Tbilisi",
    "GG": "St. Peter Port",
    "GH": "Accra",
    "GI": "Gibraltar",
    "GN": "Conakry",
    "GP": "Basse-Terre",
    "GM": "Banjul",
    "GW": "Bissau",
    "GQ": "Malabo",
    "GR": "Athens",
    "GD": "St. George's",
    "GL": "Nuuk",
    "GT": "Guatemala City",
    "GF": "Cayenne",
    "GU": "Hag\u00e5t\u00f1a",
    "GY": "Georgetown",
    "HK": "City of Victoria",
    "HN": "Tegucigalpa",
    "HR": "Zagreb",
    "HT": "Port-au-Prince",
    "HU": "Budapest",
    "ID": "Jakarta",
    "IM": "Douglas",
    "IN": "New Delhi",
    "IO": "Diego Garcia",
    "IE": "Dublin",
    "IR": "Tehran",
    "IQ": "Baghdad",
    "IS": "Reykjavik",
    "IL": "Jerusalem",
    "IT": "Rome",
    "JM": "Kingston",
    "JE": "Saint Helier",
    "JO": "Amman",
    "JP": "Tokyo",
    "KZ": "Astana",
    "KE": "Nairobi",
    "KG": "Bishkek",
    "KH": "Phnom Penh",
    "KI": "South Tarawa",
    "KN": "Basseterre",
    "KR": "Seoul",
    "XK": "Pristina",
    "KW": "Kuwait City",
    "LA": "Vientiane",
    "LB": "Beirut",
    "LR": "Monrovia",
    "LY": "Tripoli",
    "LC": "Castries",
    "LI": "Vaduz",
    "LK": "Colombo",
    "LS": "Maseru",
    "LT": "Vilnius",
    "LU": "Luxembourg",
    "LV": "Riga",
    "MF": "Marigot",
    "MA": "Rabat",
    "MC": "Monaco",
    "MD": "Chi\u0219in\u0103u",
    "MG": "Antananarivo",
    "MV": "Mal\u00e9",
    "MX": "Mexico City",
    "MH": "Majuro",
    "MK": "Skopje",
    "ML": "Bamako",
    "MT": "Valletta",
    "MM": "Naypyidaw",
    "ME": "Podgorica",
    "MN": "Ulan Bator",
    "MP": "Saipan",
    "MZ": "Maputo",
    "MR": "Nouakchott",
    "MS": "Plymouth",
    "MQ": "Fort-de-France",
    "MU": "Port Louis",
    "MW": "Lilongwe",
    "MY": "Kuala Lumpur",
    "YT": "Mamoudzou",
    "NA": "Windhoek",
    "NC": "Noum\u00e9a",
    "NE": "Niamey",
    "NF": "Kingston",
    "NG": "Abuja",
    "NI": "Managua",
    "NU": "Alofi",
    "NL": "Amsterdam",
    "NO": "Oslo",
    "NP": "Kathmandu",
    "NR": "Yaren",
    "NZ": "Wellington",
    "OM": "Muscat",
    "PK": "Islamabad",
    "PA": "Panama City",
    "PN": "Adamstown",
    "PE": "Lima",
    "PH": "Manila",
    "PW": "Ngerulmud",
    "PG": "Port Moresby",
    "PL": "Warsaw",
    "PR": "San Juan",
    "KP": "Pyongyang",
    "PT": "Lisbon",
    "PY": "Asunci\u00f3n",
    "PS": "Ramallah",
    "PF": "Papeet\u0113",
    "QA": "Doha",
    "RE": "Saint-Denis",
    "RO": "Bucharest",
    "RU": "Moscow",
    "RW": "Kigali",
    "SA": "Riyadh",
    "SD": "Khartoum",
    "SN": "Dakar",
    "SG": "Singapore",
    "GS": "King Edward Point",
    "SJ": "Longyearbyen",
    "SB": "Honiara",
    "SL": "Freetown",
    "SV": "San Salvador",
    "SM": "City of San Marino",
    "SO": "Mogadishu",
    "PM": "Saint-Pierre",
    "RS": "Belgrade",
    "SS": "Juba",
    "ST": "S\u00e3o Tom\u00e9",
    "SR": "Paramaribo",
    "SK": "Bratislava",
    "SI": "Ljubljana",
    "SE": "Stockholm",
    "SZ": "Lobamba",
    "SX": "Philipsburg",
    "SC": "Victoria",
    "SY": "Damascus",
    "TC": "Cockburn Town",
    "TD": "N'Djamena",
    "TG": "Lom\u00e9",
    "TH": "Bangkok",
    "TJ": "Dushanbe",
    "TK": "Fakaofo",
    "TM": "Ashgabat",
    "TL": "Dili",
    "TO": "Nuku'alofa",
    "TT": "Port of Spain",
    "TN": "Tunis",
    "TR": "Ankara",
    "TV": "Funafuti",
    "TW": "Taipei",
    "TZ": "Dodoma",
    "UG": "Kampala",
    "UA": "Kyiv",
    "UY": "Montevideo",
    "US": "Washington D.C.",
    "UZ": "Tashkent",
    "VA": "Vatican City",
    "VC": "Kingstown",
    "VE": "Caracas",
    "VG": "Road Town",
    "VI": "Charlotte Amalie",
    "VN": "Hanoi",
    "VU": "Port Vila",
    "WF": "Mata-Utu",
    "WS": "Apia",
    "YE": "Sana'a",
    "ZA": "Pretoria",
    "ZM": "Lusaka",
    "ZW": "Harare"
};
